### PR TITLE
refactor: step-by-step guide styling

### PR DESCRIPTION
**Pull request by Jatewo**
## Description
Styling of the step-by-step guide with lift and piste icons and names.

## Screenshots
image

### CODE REVIEW

**Review by MortenMunk — APPROVED** [review]
LGTM

**Review by Mafusn — APPROVED** [review]
LGTM

**Review by MortenMunk — APPROVED** [review]
Looks good, because I made it 😆

**Review by TheMOHD3886 — APPROVED** [review]
gg

**Pull request merged**
